### ISSUE TITLE
Value of type 'ARFrame' has no member 'viewTrans' 

### ISSUE THREAD

**Issue by kmmarie777** [ZEISS/iPad_TrueDepth_Issue_App#2]
I can't figure out how to solve this error --> `Value of type 'ARFrame' has no member 'viewTrans'`

nothing came up when I tried googling the error.

**Comment by lindemeier** [comment]
https://stackoverflow.com/questions/72440887/value-of-type-arframe-has-no-member-viewtrans

**Comment by lindemeier** [comment]
fixed in https://github.com/ZEISS/iPad_TrueDepth_Issue_App/pull/3
